language: python
python: 2.7
sudo: required
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=py26,coveralls
    - TOXENV=py27,coveralls
    - TOXENV=py33,coveralls
    - TOXENV=py34,coveralls
    - TOXENV=pypy,coveralls
    - TOXENV=py26-nocover
    - TOXENV=py27-nocover
    - TOXENV=py33-nocover
    - TOXENV=py34-nocover
    - TOXENV=pypy-nocover
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe
script:
  - ./run 'docker run -d -p 5280:5280 -p 4560:4560 -e "EJABBERD_REGISTER_TRUSTED_NETWORK_ONLY=true" -e "EJABBERD_ADMIN=admin@example.com" -e "EJABBERD_ADMIN_PWD=admin" -e "XMPP_DOMAIN=example.com" -e "EJABBERD_MUC_CREATE_ADMIN_ONLY=true" -e "EJABBERD_REGISTER_ADMIN_ONLY=true" -e "EJABBERD_MOD_ADMIN_EXTRA=true" -e "EJABBERD_MOD_MUC_ADMIN=true" dirkmoors/ejabberd'
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: always
